### ISSUE TITLE
Problems when many players are dumped simultaneously into the lobby

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#5]
I'm still investigating this issue, but wanted to post it to keep track of my progress, as per Abdullah's recommendation.

**Background:**  
I have a funnel system that keeps people at a waiting page---instructions and consent happens prior to this waiting page---and then dumps them all into the lobby at the exact same time.

This has posed various problems, with one of the main odd symptoms in the database being that players are assigned to multiple games with accompanying duplicate "player_rounds."  

The real problematic symptom is described in 'the outcome' below.

**Today's scenario:**   
There were 10 batches open, each batch had 1 game with room for N=20 people, all ten were with the same treatment.  [The idea was that they'd fill up iteratively, ensuring that I got as many full groups of 20 as possible with the remainder dumped into a partial group.  So if, eg, 96 people came in, I'd get 4 groups of 20 and a group of 16.   I don't really know how else to do this with Empirica.]

Approximately 90 users were funneled simultaneously into the lobby.  Servers:  Galaxy "quad" cluster, Atlas MongoDB M10 all on AWS east.

**The outcome** 
Many players went straight to exitStatus="gameFull" despite there being (still being) batches open.  One group of 20 individuals was assigned to 4 games, all with the same lobbyId.  They did actually successfully play, and all their data was attached gameId, with the rest being NA.

**Any insight on how I can work around this would be great!**  
I really want to start the games simultaneously; I consider it best practice for MTurkers, and it saves me some money b/c I don't pay them for waiting time.  I tell them the game will start at exactly 2pm, and I start with whomever is on the page at that time.  Most importantly, my funnel system requires people to maintain an 'active login' by clicking a button every 30 seconds.  With the default Empirica setup, someone might wander off while waiting for a game to start, and then end up being an empty datapoint.

E.g., one option I'm considering is adding the timer to an "instructions" page, so that people complete consent on the server (and are assigned to a condition as they file in asynchronously) and then are simply assigned to a game all at once, rather than the game & lobby assignment happening all at once for everyone.  Within that, I could add a random 0-5 second stagger to spread people apart.  But i'm hoping to find a way to truly simultaneously start many games at once.

**Comment by amaatouq** [comment]
> With the default Empirica setup, someone might wander off while waiting for a game to start, and then end up being an empty datapoint.

Not if you choose a lobby configuration where the timeout is 30 seconds at the individual level (rather than lobby level) and some high number of prompts, right?

>Many players went straight to exitStatus="gameFull" despite there being (still being) batches open. 

Which version of empirica are you using? (if you know the version you forked?)
A similar issue was fixed in early August.

**Comment by joshua-a-becker** [comment]
last git pull from empirica was on sept 12

have there been any updates that would impact this?

i think i'm going to take this moment to finally update my core anyway, but it would be useful to know if there were any changes to the game assignment process before i try this method again.

**Comment by joshua-a-becker** [comment]
in addition to my interest in synchronizing start time for other reasons,  I went this route b/c when I test the "individual" lobby (same version from Sept 12---just tested it now) people get assigned to a game when the dialogue box is open, so it doesn't prevent them from being assigned to a game if they walked away from their computer.   I'll check on that when I update.

**Comment by joshua-a-becker** [comment]
as far as i can tell from a git diff, there have been no updates to any of the API methods since i last pulled, or anything else that would have fixed this :/   (whatever "this" is---i still don't get what's going on)

**Comment by joshua-a-becker** [comment]
@npaton i'd be really curious if you have any insights into this.  for now, i'm going to attempt to solve the problem by introducing an artificial delay of up to 20 seconds (random number) for each user, to spread the dump into the lobby out but still get people basically synchronized with start times.   but i'm a bit concerned that won't work b/c that would still have 5 people per second entering the game.

edit:  the ability to dump large number of people into the system simultaneously seems to me a valuable feature.

**Comment by joshua-a-becker** [comment]
Was able to replicate the behavior with headless browser (RSelenium) bots:  many users sent to "gameFull" while other users started half-empty games.  (or are they half full....?)

What's weird is that there appear to be more games than batches should allow:  each batch has a "game count" = 1, but there are multiple unique gameId for each batchId.   this supports my suspicion that the db calls are not being handled sequentially in an appropriate way.

i.e., since the platform uses an "agent based" approach to game population---each user independently checks the status of the lobbies, and finds a game to enter---there may be two people making a simultaneous call, thinking a batch is open, and jumping in to create new lobbies.  maybe???

i'm done trying to explain this phenomenon since that's way out of my skill level, and i'm now going to see if i can just find some workarounds.

**Comment by joshua-a-becker** [comment]
I tried adding a random delay up to 10 seconds;  this failed for 45 users:  20 were assigned to a game (entirely filling the batch) and the other 25 were set exitStatus=full

**Comment by amaatouq** [comment]
This is beyond my expertise, but I am guessing you are right. It has to do with the simultaneous  calls .. I don’t know if Nicolas has ideas about fixing things at the assignment level (as in blocking so assignment calls are sequential)

**Comment by joshua-a-becker** [comment]
my next step is:   determine whether the problem is in the players/methods.js api or the games/create.js api--currently those both set identical exitStatuses so i'm going to disambiguate them.

[because it's very odd to me that in my 45 user test, there were 25 users turned away when their player$lobbyId points to a lobby that is open, and they're queued, which makes me think its happening in create.js]

**Comment by joshua-a-becker** [comment]
Actually, now I'm unable to replicate that 45 user test---things seem to be working _pretty _well_ with a 10 second dispersal delay.   I'll keep testing this to see if it's reliable but I might have a workable fix for now.

**Comment by npaton** [comment]
Sorry I'm late to the party! I was knocked out last 48h by a nasty flu type thing, and was on vacation previously. I've been seeing messages of your issue go by and I've been meaning to look at it, sorry for the delay!! Anyway, yes, ok, I see the problem.

So if I understand well, there are no intro steps, and you are using `playerIdParam`, the 2 of which, combined with the fact you send everyone in at once, should make the game start at once for a group of players, right?

That is an interesting scenario. Definitely something we should be able to support. I'll be frank with you, the assignment algorithm we're using right now sucks. It is a patchwork and one of the big projects we want to work on next. We want to give the game designer full control over assignment with callbacks, so that a scenario like yours could be easily modelled, hopefully.

But that will take a while. In the mean time, I need to tighten up the current assignment. It is supposed to be able to handle concurrent assignment, exactly as you're doing, but our setup is far from perfect for this (Mongo does not support transactions, so we're simulating locks, not very well apparently).

I have a few questions to help me debug the issue:
- You made no changes to the core that might affect assignment?
- You are deploying on a single container in Galaxy, correct? (currently Empirica does not support mutli-servers deployments)
- Could you give me access to the code so I can run some tests on it directly?
- Have you moved to the new Empirica packaging? I am not expecting to maintain the old fork mode much longer, and I'd be glad to help you transition to the new model. It is not as friendly to core overrides (as we hope it becomes less and less useful over time), but it is still possible and I can show you how.
- Would you have a DB dump of a session that did go well, so I can see how the over-assignment  looks like in the DB?

Thank you for your help. Hopefully I should be able to help fix soon.

**Comment by npaton** [comment]
To skip intro steps, are you just not returning any intro steps for the introSteps callback, or are you using "debug mode", starting the batch in the admin while pressing cmd or ctrl?

Edit: I don't think you're using the "debug mode", that would be even more broken.

**Comment by npaton** [comment]
Hum. Reading through the code about this, I think I see the problem with players getting `gameFull`. It'
s kind of an expected behavior, in a sense. On player creation, we assign the player to the first unfilled batch, which if it only contains one game and we throwing players at the app, we will probably overbook that game. Normally, we have an overflow system that will push players to the next batch if possible, but that's only if they haven't already reached the lobby (haven't completed the intro steps yet, which in this case, they complete instantly). If they are already in the lobby, they are lead to gameFull if the game starts and we have an overbooking. This is decision we took at the time as it wasn't expected to happen much, but with this specific scenario, no intro steps and all players arriving at once, it is absolutely bound to happen. 2 things which normally take time (people arriving and intro steps) are now immediate. This decision to push people to gameFull is something we can revise. But it could "break" other cases, where players might be waiting multiple times their lobby timeout period in successive lobbies they might be assigned to. So not sure what to do there, yet.

But I'm not sure about the "players are assigned to multiple games" issue though. They can be assigned to multiple lobbies, the overbooking overflow behavior does not cleanup behind itself, it should, I'm not happy with that, but it shouldn't break anything. I don't understand how that can happen. I might have misunderstood the issue here. I think I'll need a DB dump.

**Comment by joshua-a-becker** [comment]
Ok good.  So most of this is explained as expected behavior.  The multiple-game-assignment is weird, but does not seem to cause the problem.

- yes, one quad container on Galaxy
- correct, no consent or instructions (an empty array) but have playerIdParam in url
- currently experimenting with adding an instructions step--thats where I now add a random waiting period.  Won't solve the problem though, I now understand, if people are still en masse entering the lobby.  
- Sounds like I'd have the same problem if people en mass enter the lobby even without my features--i will test that with browser bots (happy to share R code for that as well)
- any guess for what rate of entry would be safe?
- no core changes that impact this, as far as I can tell.  Only changes to core are for new admin feature and  publiccontainer logic. To be more confident, I'm going to rebuild this using the production version and set the timer as an instructions page, no changes to core.  I don't do this in general because I like to set the time as a global config (a feature I built into admin) too hard to set it as a new condition every time.  I also need to modify bc I have a "password" like check.  
- for example of multiple game assignment, see: https://github.com/empiricaly/empirica/issues/78
- happy to share db dump but I want to curate it to make things easy for you--can you clarify, you want a game that did go well or did not go well?
- the multiple games thing seems to be relatively rare, in retrospect.  I now realize the main problem for me is the expected behavior.
- will share current git, will follow up soon with a version using the new package.

Sorry for brevity--on mobile.  Out of office this coming week, won't have many work hours, sorry for delays & mobile stylings.

**Comment by joshua-a-becker** [comment]
upon reflection:  i'm should be able to quickly write up a simple version tomorrow w/ standard production using an instructions page for a timer, and just manually setting "global configs" in the DB for the time, and i can just create the mongo subscription script right in the experimenter zone.  

will report back; i'll hold off on sharing any code until then since this will make it a lot easier for you to follow.  and who knows, maybe it will all magically work once i update & use the instructions page.

p.s. feel better soon! 😷 ☕ 💤  📺

**Comment by npaton** [comment]
Thank you @joshua-a-becker.

> happy to share db dump but I want to curate it to make things easy for you--can you clarify, you want a game that did go well or did not go well?

The one(s) that did not go well. I'm most interested by the one player assigned to multiple games issues.

Let me know how it goes with the things you want to test. If you can get this to work as is, it might be better than working too hard on fixing the core, and allocate that time instead into the complete rework of assignment we want to do anyway. For that work, I'd actually like to pick you brain, we should plan a meeting soon with @amaatouq to talk about this. I want to build a scalable solution, something that can adapt to many scenarios, yet be simple to understand.

**Comment by joshua-a-becker** [comment]
replicated problem using standard `npx create-empirica-app` with no core modifications, saved datadump in github.  created issue #11 to track this specific possible-bug

https://github.com/empiricaly/meteor-empirica-core/issues/11

**Comment by joshua-a-becker** [comment]
y'alls call whether to leave this issue open (i'm now going to try to get it to work, using tricks like 20 second delays, happy to track my progress) or close it.

i will also be following up on this issue once the assignment feature is exposed to experimenters, which should theoretically allow a proper solution to the problem

p.s. not sure if i've already said it elsewhere, the new beta version looks amazing!  so cool!

**Comment by npaton** [comment]
I'd be interested in keeping track with the solution you come up with, if you don't mind keeping at logging that here.

And I am closing the issue if you think it is something you can workaround for now, knowing that we are working on the overall solution: better assignment.

**Comment by joshua-a-becker** [comment]
i've been using the following solution, which works OK:  randomly add up to 60 seconds to each person's "start time", to disperse the influx over the course of a minute.

with 100 users, I typically lose about 15 due to overlap.
